# Generated by Django 4.2.17 on 2024-12-13 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cidade',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='contato',
            field=models.CharField(max_length=100, verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='funcao',
            field=models.CharField(max_length=100, verbose_name='Tipo de Serviço Prestado'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
